version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

  spring-boot:
    build: .
    container_name: test_springbok_project
    environment:
      SERVER_PORT: 8080
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USERNAME: batchlcwd@gmail.com
      EMAIL_PASSWORD: dqwxmxfvukvwhnkh
      EMAIL_DOMAIN: batchlcwd@gmail.com
      CLOUDINARY_API_KEY: 575233445171369
      CLOUDINARY_API_SECRET: WF88TQpJyKATyZCv4o4M0dx3xEQ
      CLOUDINARY_NAME: derpgrwbe
    ports:
      - "8082:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
